apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: node-app  
        image: gcr.io/souhayelproject/gcpdevops
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
